server:
  port: ${PORT:8080}

spring:
  application:
    name: crypto-app

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

binance:
  base-url: https://api.binance.com

  app:
    trading:
      symbol: BTCTRY
      interval: 5m
      limit: 100

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}

  chat:
    id: ${TELEGRAM_CHAT_ID}